list/urls.py
from django.urls import path
from .views import *

app_name = "list"

urlpatterns = [
    path('', home, name="home"),
    path('<int:list_id>', list_view, name="list_view"),
    path('create-list', create_list, name="create_list"),
    path('delete-list/<int:list_id>', delete_list, name="delete_list"),
    path('delete-task/<int:task_id>', delete_task, name="delete_task"),
    path('check-task/<int:task_id>', change_task_status, name="check_task"),
    path('change-task-content/<int:task_id>/<str:content>', change_task_content, name="change-task-content"),
]

register/urls.py
from django.urls import path
from .views import register

app_name = 'register'

urlpatterns = [
    path('', register, name="create"),
]

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('register/', include('register.urls', namespace='register')),
    path('', include('list.urls', namespace="list"))
]

list/models.py
from django.db import models
from django.contrib.auth.models import User


class List(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    

class Task(models.Model):
    content = models.CharField(max_length=100)
    done = models.BooleanField(default=False)
    task_list = models.ForeignKey(List, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content

register/models.py
from django.db import models

# Create your models here.

list/forms.py
from django import forms

class CreateListForm(forms.Form):
    list_name = forms.CharField(max_length=50, required=True, label="List Name")


class AddTaskForm(forms.Form):
    task_content = forms.CharField(max_length=1000, required=True, label="Task Content")
    done = forms.BooleanField(required=False)

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=50)
    
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

list/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import List, Task
from .forms import *
import json

def home(request):
    user = request.user
    lists = List.objects.filter(user=user.id)
    return render(request, 'list/home.html', {'lists': lists})

def list_view(request, list_id):
    lst_query = List.objects.filter(id=list_id, user=request.user)
    if lst_query.exists():
        lst = lst_query[0]
        tasks = Task.objects.filter(task_list=lst)
        if request.method == "POST":
            task_form = AddTaskForm(request.POST)
            if task_form.is_valid():
                content = task_form.cleaned_data['task_content']
                done = task_form.cleaned_data['done']
                new_task = Task(content=content, done=done, task_list=lst)
                new_task.save()
                task_form = AddTaskForm()
            else:
                print(task_form.errors)
            return render(request, 'list/list.html', {'list': lst, 'list_tasks': tasks, 'task_form': task_form})
        task_form = AddTaskForm()
        return render(request, 'list/list.html', {'list': lst, 'list_tasks': tasks, 'task_form': task_form})
    return render(request, 'list/list.html')



def change_task_status(task_id):
    payload = {}
    tasks = Task.objects.filter(id=task_id)
    if tasks.exists():
        task = tasks[0]
        if task.done:
            task.done = False
            payload['response'] = "Changed To False"
            print('changed to false')
        else:
            task.done = True
            payload['response'] = "Changed To True"
            print('changed to true')
        task.save()
    else:
        payload['response'] = "Task does not exist"
        print('task doesnot exist')
    return HttpResponse(json.dumps(payload), content_type="application/json")

def change_task_content(request, task_id, content):
    payload = {}
    if request.method == "GET":
        task_id = task_id
        tasks = Task.objects.filter(id=task_id)
        if tasks.exists():
            task = tasks[0]
            task.content = content
            task.save()
            payload['response'] = "Task Updated."
        else:
            payload['response'] = "Task not found."
    return HttpResponse(json.dumps(payload), content_type="application/json")
  
def create_list(request):
    if request.method == "POST":
        f = CreateListForm(request.POST)
        if f.is_valid():
            lst_name = f.cleaned_data['list_name']
            lst = List(name=lst_name, user=request.user)
            lst.save()
            return redirect('/')
        else:
            print(f.errors)
        return render(request, 'list/createList.html', {'form': f})
    f = CreateListForm()
    return render(request, 'list/createList.html', {'form': f})

def delete_list(request, list_id):
    List.objects.filter(id=list_id).delete()
    return redirect('/')

def delete_task(request, task_id):
    task_query = Task.objects.filter(id=task_id)
    if task_query.exists():
        task = task_query[0]
        lst = task.task_list
        task.delete()
        return redirect(f'/{lst.id}')
    return redirect('/')

register/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method == "POST":
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect('/')
    else:
        f = UserCreationForm()
    
    return render(request, 'register/register.html', {'form': f})

list/templates/list/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="/static/css/base.css">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
  </head>
  <body>
    
  
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'list:home' %}">To Do List</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'list:home' %}">Home</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div class="container">
          <div class="base-container">
    {% block content %}
      
    {% endblock %}
    </div>
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  </body>
</html>

list/templates/list/createList.html
{% extends 'list/base.html' %}
{% block title %}
    Create List
{% endblock title %}

{% block content %}
    <h1>Create List</h1>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-primary">Create List</button>
    </form>
{% endblock content%}

list/templates/list/home.html
{% extends 'list/base.html' %} {% block title %} Home {% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        {% if lists %}
            <h4>Your Lists</h4>
            {% for lst in lists %}
            <br>
            <a href="{% url 'list:list_view' list_id=lst.id %}" class="list-links">{{ lst }}</a>
                
            {% endfor %}

        {% else %}

            <p>Not lists available</p>
        
        {% endif%}
        <br><br>
        <a href="{% url 'list:create_list' %}" class="btn btn-primary">Create a new list</a>
        
        <br>
        <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
    {% else %}
        <p>You are not logged in.</p>
        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
        <p>Don't Have An Account?<a href="{% url 'register:create' %}" class="link">Sign Up</a></p>
    {% endif %}
{% endblock content %}

list/templates/list/list.html
{% extends 'list/base.html' %}
{% load static %}

{% block title %}
    List
{% endblock title %}

{% block content %}

    {% if list %}

        <h2>{{list.name}}</h2>
        {% if list_tasks %}
        <div id="tasks">
            {% for task in list_tasks %}
                <div class="task">
                    <div name="{{task.id}}">
                        {% if task.done %}
                            <input type="checkbox" checked="true" class="task-checkbox"/>
                        {% else %}
                            <input type="checkbox" class="task-checkbox"/>
                        {% endif %}
                    </div>
                    <input name="{{task.id}}" value="{{task}}" class="task-content-input"/>
                    <a name="delete" href="{% url 'list:delete_task' task_id=task.id %}" class="btn btn-warning delete-link">Delete Task</a>
                    
                </div>
            {% endfor %}
        {% else %}
            <p>No Tasks</p>
        
        {% endif %}

        
        <form method="post" class="add-task-form">
            <h4>Add a Task</h4>
            {% csrf_token %}
            {{task_form}}
            <button type="submit" class="btn btn-secondary">Add Task</button>
        </form>

        <a href="{% url 'list:delete_list' list_id=list.id%}" class="btn btn-danger">Delete List</a>
    
    {% else %}
        <h3>No List</h3>
    {% endif %}
<script src="{% static 'js/list/checkTask.js' %}" type="text/javascript" ></script>

{% endblock content %}

register/templates/register/register.html
{% extends 'list/base.html' %} 
{% block title %} Create User {% endblock %} 
{% block content %}
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Register</button>
    </form>
{% endblock content %}